### ISSUE TITLE
.gitignore mess

### ISSUE THREAD

**Issue by orsjb** [orsjb/HappyBrackets#12]
Lots of files being ignored that we don't want to ignore. 
The HappyBrackets Project config folder entirely missing. The HappyBrackets Project IML file missing. Some stuff in Distribution missing.

**Comment by samgwise** [comment]
We probably need to refactor how we lay out our .gitignore files.

We should have one .gitignore per project tree. I think some of these problems may be from copying .gitignore files from the HappyBrackets project directory into the distribution tree.

For example there is a .gitignore file in the HappyBrackets/config directory which ignores *.json, this behaviour allows us to have the default files which are then overridden by user created .json files and the user created files will not be committed and will not clobber anyone else's config files.

**Comment by orsjb** [comment]
Done a clean up. Prob not perfect still, but clean at least.
