### ISSUE TITLE
Broadcast listeners are also receiving /device/alive messages

### ISSUE THREAD

**Issue by orsjb** [orsjb/HappyBrackets#21]
Broadcast listeners are also receiving /device/alive messages. Does this mean they're listening all on the same channel? Is /device/alive now being broadcast? That would make sense and if so this is not necessarily an issue. Only if that's a mistake. Still it might be sensible to have a different channel for these messages.

**Comment by samgwise** [comment]
Yes I believe that is the correct behavior for the current design.

**Comment by orsjb** [comment]
I've added an 'else' clause to so that only messages not already consumed by the DeviceConnection manager get forwarded to listeners.

**Comment by orsjb** [comment]
Sorry that should read the net.happybrackets.device.network.NetworkCommunication class.
