### ISSUE TITLE
Network connection and communication issues

### ISSUE THREAD

**Issue by orsjb** [orsjb/HappyBrackets#26]
> HB plugin freezes when it is instantiated when on Wifi with a device connected. It doesn’t spin when Wifi is off.

I believe this is fixed in 1.6.4.  The Controller advertiser has had its start delayed until after the toolwindow is created. What was happening was the device was being added to observable list before window was actually ready to receive the messages.

> Java incompatibility on older devices - what is the magic number issue?
- We require Java 8 for the calls we are using in the plugin

Device logging is erratic. Seems to require sequence of actions: select device, then turn on device logging. But this also doesn't always work. Also when working seems to have missing data or not update properly.

> When trying to connect to the router via Ethernet the devices aren't found: in general there are still issues with automatically discovering and reconnecting to the server under different network conditions and whenever the connection is lost and re-established.

This is corrected

**Comment by angelofraietta** [comment]
This should be tested now as I believe network issue are fixed in version 1.2.0.
Some bugs were fixed and a broadcast message was added in addition to multicast.
