### ISSUE TITLE
Plugin GUI layout - sometimes the buttons for sending OSC commands are hidden

### ISSUE THREAD

**Issue by orsjb** [orsjb/HappyBrackets#33]
Occasionally (not sure what the reproduction conditions are) the panel displaying custom OSC commands has the lowest row of buttons half-hidden.

**Comment by angelofraietta** [comment]
I have had a look at this. This happens whenever the Debug or the Devices window is expanded

**Comment by angelofraietta** [comment]
This is fixed. I made minimum size in makeCompositionPane to 300.
