### ISSUE TITLE
Raspberry Pi is not connecting the the given WiFi credentials

### ISSUE THREAD

**Issue by orsjb** [orsjb/HappyBrackets#7]
Tested on a D-Link. The Pi is available when connected via ethernet but simply fails to connect to this particular router. It might be because of something specific to the configuration of the router, so it would be good to know if this is working anywhere at the moment.

**Comment by samgwise** [comment]
Is this via the OSC message  to /PI/config/wifi of the deivce? (See net.happybrackets.device.network.NetworkCommunication line 90-99 of commit 18b0e16)

**Comment by orsjb** [comment]
No, I've not heard of this message before. 
The /etc/network/interfaces file is correct but the wifi is not connecting. I'm trying to manually set it with ifdown and ifup. Possibly it is a problem with my router.

**Comment by orsjb** [comment]
Note: I don't know about these OSC messages. Where are we documenting them?
Also: it should be /device/ rather than /PI/.

**Comment by samgwise** [comment]
I haven't fully tested the message behaviour yet so I haven't added it to any extant documentation. and the /PI/ was a typo, it has always been /device/.

**Comment by orsjb** [comment]
Resolved.
